import type { AssetKind } from './types';

// Everything BattyFlow can download, pinned to an exact file and SHA-256. Downloads only start when
// you click a button, and a file is only used if its hash matches. Hashes come from the publishers:
// GitHub release asset digests and Hugging Face LFS object ids (checked 2026-10-01).
export interface CatalogItem {
  id: string;
  kind: AssetKind;
  name: string;
  blurb: string;
  url: string;
  sha256: string;
  size: number;
  /** For zip archives: the executable inside the archive. */
  entry?: string;
  version: string;
  license: string;
  provenance: string;
  languages: readonly string[];
  /** Relative speed and accuracy, 1-5, for the model picker. */
  speed?: number;
  accuracy?: number;
  gpu?: boolean;
  recommended?: boolean;
}

// Whisper's multilingual vocabulary (tokenizer language codes).
export const whisperLanguages = [
  'en',
  'zh',
  'de',
  'es',
  'ru',
  'ko',
  'fr',
  'ja',
  'pt',
  'tr',
  'pl',
  'ca',
  'nl',
  'ar',
  'sv',
  'it',
  'id',
  'hi',
  'fi',
  'vi',
  'he',
  'uk',
  'el',
  'ms',
  'cs',
  'ro',
  'da',
  'hu',
  'ta',
  'no',
  'th',
  'ur',
  'hr',
  'bg',
  'lt',
  'la',
  'mi',
  'ml',
  'cy',
  'sk',
  'te',
  'fa',
  'lv',
  'bn',
  'sr',
  'az',
  'sl',
  'kn',
  'et',
  'mk',
  'br',
  'eu',
  'is',
  'hy',
  'ne',
  'mn',
  'bs',
  'kk',
  'sq',
  'sw',
  'gl',
  'mr',
  'pa',
  'si',
  'km',
  'sn',
  'yo',
  'so',
  'af',
  'oc',
  'ka',
  'be',
  'tg',
  'sd',
  'gu',
  'am',
  'yi',
  'lo',
  'uz',
  'fo',
  'ht',
  'ps',
  'tk',
  'nn',
  'mt',
  'sa',
  'lb',
  'my',
  'bo',
  'tl',
  'mg',
  'as',
  'tt',
  'haw',
  'ln',
  'ha',
  'ba',
  'jw',
  'su',
  'yue',
] as const;
const qwenLanguages = ['en', 'zh', 'es', 'fr', 'de', 'it', 'pt', 'ru', 'ja', 'ko', 'vi', 'th', 'ar'] as const;

const whisperRelease = 'https://github.com/ggml-org/whisper.cpp/releases/download/b5130/';
const whisperModels = 'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/';

export const catalog: readonly CatalogItem[] = [
  {
    id: 'whisper-cpu',
    kind: 'whisper',
    name: 'whisper.cpp for CPU',
    blurb: 'Works on any 64-bit Windows PC. The right choice unless you have an NVIDIA GPU.',
    url: `${whisperRelease}whisper-bin-x64.zip`,
    sha256: 'f9ec6c52a2e949b62ab51fa21d0d497958f9e41c3010c157c4e42932d5316f3c',
    size: 8573270,
    entry: 'Release/whisper-cli.exe',
    version: '1.9.4',
    license: 'MIT',
    provenance: 'https://github.com/ggml-org/whisper.cpp/releases/tag/b5130',
    languages: [],
    recommended: true,
  },
  {
    id: 'whisper-cuda',
    kind: 'whisper',
    name: 'whisper.cpp for NVIDIA GPUs',
    blurb:
      'CUDA 12.4 with cuBLAS. Needs an NVIDIA driver from 2023 or newer. Large download, much faster with big models.',
    url: `${whisperRelease}whisper-cublas-12.4.0-bin-x64.zip`,
    sha256: 'af520ddd034d985b55dfeea3e465ed93653ba2aee1a55e865033edc548c272a7',
    size: 674539285,
    entry: 'Release/whisper-cli.exe',
    version: '1.9.4',
    license: 'MIT; includes NVIDIA CUDA runtime libraries under the NVIDIA EULA',
    provenance: 'https://github.com/ggml-org/whisper.cpp/releases/tag/b5130',
    languages: [],
    gpu: true,
  },
  {
    id: 'tiny.en',
    kind: 'asrModel',
    name: 'Tiny (English)',
    blurb: 'Fastest. Fine for short notes; misses more words.',
    url: `${whisperModels}ggml-tiny.en-q8_0.bin`,
    sha256: '5bc2b3860aa151a4c6e7bb095e1fcce7cf12c7b020ca08dcec0c6d018bb7dd94',
    size: 43550795,
    version: 'tiny.en q8_0',
    license: 'MIT',
    provenance: 'https://huggingface.co/ggerganov/whisper.cpp',
    languages: ['en'],
    speed: 5,
    accuracy: 2,
  },
  {
    id: 'base.en',
    kind: 'asrModel',
    name: 'Base (English)',
    blurb: 'The default. Quick on any laptop CPU.',
    url: `${whisperModels}ggml-base.en-q8_0.bin`,
    sha256: 'a4d4a0768075e13cfd7e19df3ae2dbc4a68d37d36a7dad45e8410c9a34f8c87e',
    size: 81781811,
    version: 'base.en q8_0',
    license: 'MIT',
    provenance: 'https://huggingface.co/ggerganov/whisper.cpp',
    languages: ['en'],
    speed: 4,
    accuracy: 3,
    recommended: true,
  },
  {
    id: 'small.en',
    kind: 'asrModel',
    name: 'Small (English)',
    blurb: 'Noticeably better with names and jargon. Wants a fast CPU or a GPU.',
    url: `${whisperModels}ggml-small.en-q8_0.bin`,
    sha256: '67a179f608ea6114bd3fdb9060e762b588a3fb3bd00c4387971be4d177958067',
    size: 264477561,
    version: 'small.en q8_0',
    license: 'MIT',
    provenance: 'https://huggingface.co/ggerganov/whisper.cpp',
    languages: ['en'],
    speed: 3,
    accuracy: 4,
  },
  {
    id: 'large-v3-turbo',
    kind: 'asrModel',
    name: 'Large v3 Turbo',
    blurb:
      'Best accuracy, 100 languages. Pair it with the NVIDIA engine; on a CPU it takes several seconds per sentence.',
    url: `${whisperModels}ggml-large-v3-turbo-q5_0.bin`,
    sha256: '394221709cd5ad1f40c46e6031ca61bce88931e6e088c188294c6d5a55ffa7e2',
    size: 574041195,
    version: 'large-v3-turbo q5_0',
    license: 'MIT',
    provenance: 'https://huggingface.co/ggerganov/whisper.cpp',
    languages: whisperLanguages,
    speed: 1,
    accuracy: 5,
  },
  {
    id: 'base',
    kind: 'asrModel',
    name: 'Base (multilingual)',
    blurb: '99 languages with automatic detection. Same speed as Base (English).',
    url: `${whisperModels}ggml-base-q8_0.bin`,
    sha256: 'c577b9a86e7e048a0b7eada054f4dd79a56bbfa911fbdacf900ac5b567cbb7d9',
    size: 81768585,
    version: 'base q8_0',
    license: 'MIT',
    provenance: 'https://huggingface.co/ggerganov/whisper.cpp',
    languages: whisperLanguages.filter(code => code !== 'yue'),
    speed: 4,
    accuracy: 3,
  },
  {
    id: 'llama-cpu',
    kind: 'llama',
    name: 'llama.cpp for CPU',
    blurb: 'Runs the optional polish model on the CPU.',
    url: 'https://github.com/ggml-org/llama.cpp/releases/download/b6532/llama-b6532-bin-win-cpu-x64.zip',
    sha256: 'ac7f2cb0ca2c2a97bff65edc8f16d6a0e596cbea5addc131721a89bab6f7a379',
    size: 14074931,
    entry: 'llama-cli.exe',
    version: 'b6532',
    license: 'MIT',
    provenance: 'https://github.com/ggml-org/llama.cpp/releases/tag/b6532',
    languages: [],
    recommended: true,
  },
  {
    id: 'qwen2.5-1.5b',
    kind: 'llmModel',
    name: 'Qwen2.5 1.5B Instruct',
    blurb: 'Fixes punctuation and filler words, drafts commands. Adds a second or two per dictation.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf',
    sha256: '6a1a2eb6d15622bf3c96857206351ba97e1af16c30d7a74ee38970e434e9407e',
    size: 1117320736,
    version: 'Qwen2.5-1.5B-Instruct Q4_K_M',
    license: 'Apache-2.0',
    provenance: 'https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF',
    languages: qwenLanguages,
    speed: 3,
    accuracy: 3,
    recommended: true,
  },
  {
    id: 'qwen2.5-0.5b',
    kind: 'llmModel',
    name: 'Qwen2.5 0.5B Instruct',
    blurb: 'Smaller and faster, but often leaves self-corrections in place.',
    url: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf',
    sha256: '74a4da8c9fdbcd15bd1f6d01d621410d31c6fc00986f5eb687824e7b93d7a9db',
    size: 491400032,
    version: 'Qwen2.5-0.5B-Instruct Q4_K_M',
    license: 'Apache-2.0',
    provenance: 'https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF',
    languages: qwenLanguages,
    speed: 4,
    accuracy: 2,
  },
];

export const catalogItem = (id: string): CatalogItem | undefined => catalog.find(item => item.id === id);
